spring.application.name=MarketplaceWebServices

# Server Configuration
    server.port=${WEB_SERVICES_PORT:8080}

# Socket Server Connection
    socket.server.host=${SOCKET_SERVER_HOST:localhost}
    socket.server.port=${SOCKET_SERVER_PORT:9090}

# Logging
    logging.level.com.marketplace=DEBUG

# JWT Configuration
    jwt.secret=your_very_long_and_secure_random_secret_key_32_characters_min
    jwt.expiration=3600000

# Database
    spring.datasource.url=jdbc:postgresql://marketplace-db-25552.j77.aws-eu-central-1.cockroachlabs.cloud:26257/marketplace_db?sslmode=verify-full
    spring.datasource.username=Arsany
    spring.datasource.password=1nFFIQWl0Mupa_hQNZ7K-Q
    spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=none
    spring.sql.init.mode=never
