name: Marketplace CI/CD

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hello World
        run: echo "GitHub Actions is working!"